"""/hapi 子命令路由元数据（纯数据，无 AstrBot 依赖）。

command_handlers 用它做路由；keyword_maps 用它判断是否可带参。
新增子命令时同步改这里与 CommandHandlers 的 handler 映射。
"""

from __future__ import annotations

# 子命令 → 是否接收参数。True = 可带参；False = 无参（关键词须整句严格匹配）
ROUTE_TAKES_ARG: dict[str, bool] = {
    "help": True,
    "帮助": True,
    "list": True,
    "ls": True,
    "sw": True,
    "s": False,
    "status": False,
    "msg": True,
    "messages": True,
    "to": True,
    "send": True,
    "retry": False,
    "perm": True,
    "model": True,
    "effort": True,
    "plan": True,
    "fast": True,
    "focus": True,
    "专注": False,
    "退出专注": False,
    "remote": False,
    "output": True,
    "out": True,
    "pending": False,
    "approve": False,
    "a": False,
    "allow": True,
    "answer": True,
    "deny": True,
    "summary": True,
    "create": True,  # 可带模板名与目录（/hapi create [模板名] [目录]）
    "abort": True,
    "stop": True,
    "archive": False,
    "resume": True,
    "reopen": True,
    "sync": True,
    "rename": False,
    "delete": False,
    "clean": True,
    "files": True,
    "file": True,
    "find": True,
    "download": True,
    "dl": True,
    "upload": True,
    "git": False,
    "diffstat": True,
    "diff": True,
    "bind": True,
    "routes": False,
    "alias": True,  # 可选过滤词
}

# 子命令 → CommandHandlers 方法名
ROUTE_HANDLERS: dict[str, str] = {
    "help": "cmd_help",
    "帮助": "cmd_help",
    "list": "cmd_list",
    "ls": "cmd_list",
    "sw": "cmd_sw",
    "s": "cmd_status",
    "status": "cmd_status",
    "msg": "cmd_msg",
    "messages": "cmd_msg",
    "to": "cmd_to",
    "send": "cmd_send",
    "retry": "cmd_retry",
    "perm": "cmd_perm",
    "model": "cmd_model",
    "effort": "cmd_effort",
    "plan": "cmd_plan",
    "fast": "cmd_fast",
    "focus": "cmd_focus",
    "专注": "cmd_focus",
    "退出专注": "cmd_focus",
    "remote": "cmd_remote",
    "output": "cmd_output",
    "out": "cmd_output",
    "pending": "cmd_pending",
    "approve": "cmd_approve",
    "a": "cmd_approve",
    "allow": "cmd_allow",
    "answer": "cmd_answer",
    "deny": "cmd_deny",
    "summary": "cmd_summary",
    "create": "cmd_create",
    "abort": "cmd_abort",
    "stop": "cmd_abort",
    "archive": "cmd_archive",
    "resume": "cmd_resume",
    "reopen": "cmd_reopen",
    "sync": "cmd_sync",
    "rename": "cmd_rename",
    "delete": "cmd_delete",
    "clean": "cmd_clean",
    "files": "cmd_files",
    "file": "cmd_files",
    "find": "cmd_find",
    "download": "cmd_download",
    "dl": "cmd_download",
    "upload": "cmd_upload",
    "git": "cmd_git",
    "diffstat": "cmd_diffstat",
    "diff": "cmd_diff",
    "bind": "cmd_bind",
    "routes": "cmd_routes",
    "alias": "cmd_alias",
}
